# Cálculo de ratios

Cálculo de los ratios financieros a partir de la información contable y bursátil disponible, que utilizaremos como variables explicativas del modelo

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.options.display.max_columns = None
pd.options.display.max_rows = 50

In [3]:
! ls -n ../tablas

total 12480
-rw-rw-r-- 1 1000 1000 9992731 ago 28 01:03 banks_cotiz.csv
-rw-rw-r-- 1 1000 1000  984636 ago 28 12:05 dataformodel.csv
-rw-rw-r-- 1 1000 1000  578247 ago 28 01:03 mergedbalres.csv
-rw-rw-r-- 1 1000 1000  683261 ago 28 01:03 registros_etiq.csv
-rw-rw-r-- 1 1000 1000  525808 ago 30 22:58 registros_etiq_normal.csv
-rw-rw-r-- 1 1000 1000    1997 ago 30 22:58 var_indice.csv

In [4]:
data = pd.read_csv('../tablas/registros_etiq_normal.csv', usecols=['Ticker',
                                                             'Fiscal Year',
                                                             'Fiscal Period',
                                                             'Publish Date',
                                                             'Shares (Basic)',
                                                             'Shares (Diluted)',
                                                             'Cash, Cash Equivalents & Short Term Investments',
                                                             'Interbank Assets',
                                                             'Short & Long Term Investments',
                                                             'Accounts & Notes Receivable',
                                                             'Net Loans',
                                                             'Net Fixed Assets',
                                                             'Total Assets',
                                                             'Total Deposits',
                                                             'Short Term Debt',
                                                             'Long Term Debt',
                                                             'Total Liabilities',
                                                             'Preferred Equity',
                                                             'Share Capital & Additional Paid-In Capital',
                                                             'Treasury Stock',
                                                             'Retained Earnings',
                                                             'Total Equity',
                                                             'Total Liabilities & Equity',
                                                             'Revenue',
                                                             'Provision for Loan Losses',
                                                             'Net Revenue after Provisions',
                                                             'Total Non-Interest Expense',
                                                             'Operating Income (Loss)',
                                                             'Non-Operating Income (Loss)',
                                                             'Pretax Income (Loss)',
                                                             'Income Tax (Expense) Benefit, Net',
                                                             'Income (Loss) from Continuing Operations',
                                                             'Net Extraordinary Gains (Losses)',
                                                             'Net Income',
                                                             'Net Income (Common)',
                                                             'Periodo',
                                                             'Price_d',
                                                             'Price_d_100',
                                                             'Publish_Date+180',
                                                             'Price_d+180_100',
                                                             'Price_d+180',
                                                             'Indice_d_100',
                                                             'Indice_d+180_100',
                                                             'Var_cotiz',
                                                             'Var_index',
                                                             'Etiqueta'])

In [5]:
len(data)

1021

In [6]:
list(data.columns)

['Ticker',
 'Fiscal Year',
 'Fiscal Period',
 'Publish Date',
 'Shares (Basic)',
 'Shares (Diluted)',
 'Cash, Cash Equivalents & Short Term Investments',
 'Interbank Assets',
 'Short & Long Term Investments',
 'Accounts & Notes Receivable',
 'Net Loans',
 'Net Fixed Assets',
 'Total Assets',
 'Total Deposits',
 'Short Term Debt',
 'Long Term Debt',
 'Total Liabilities',
 'Preferred Equity',
 'Share Capital & Additional Paid-In Capital',
 'Treasury Stock',
 'Retained Earnings',
 'Total Equity',
 'Total Liabilities & Equity',
 'Revenue',
 'Provision for Loan Losses',
 'Net Revenue after Provisions',
 'Total Non-Interest Expense',
 'Operating Income (Loss)',
 'Non-Operating Income (Loss)',
 'Pretax Income (Loss)',
 'Income Tax (Expense) Benefit, Net',
 'Income (Loss) from Continuing Operations',
 'Net Extraordinary Gains (Losses)',
 'Net Income',
 'Net Income (Common)',
 'Periodo',
 'Price_d',
 'Price_d_100',
 'Publish_Date+180',
 'Price_d+180',
 'Price_d+180_100',
 'Indice_d_100',
 'Indice_d+180_100',
 'Var_cotiz',
 'Var_index',
 'Etiqueta']

### Capitalización bursátil

In [7]:
data['Capit']=data['Shares (Basic)']*data['Price_d']
len(data[data['Capit'].isnull()])

30

### PER

In [8]:
data['PER'] = data['Capit']/data['Net Income (Common)']
len(data[data['PER'].isnull()])

30

### Price / Book Value

In [9]:
data['PBC'] = data['Capit']/data['Total Equity']
len(data[data['PBC'].isnull()])

30

### ROE

In [10]:
data['ROE'] = data['Net Income (Common)']/data['Total Equity']
len(data[data['ROE'].isnull()])

0

### ROA

In [11]:
data['ROA'] = data['Net Income (Common)']/data['Total Assets']
len(data[data['ROA'].isnull()])

0

### Deuda total / FFPP

In [12]:
data['Deuda_FFPP'] = (data['Short Term Debt'] + data['Long Term Debt'])/data['Total Equity']
len(data[data['Deuda_FFPP'].isnull()])

252

### Deuda corto plazo / FFPP

In [13]:
data['DeudaCP_FFPP'] = data['Short Term Debt'] / data['Total Equity']
len(data[data['DeudaCP_FFPP'].isnull()])

101

### Dotación en el periodo / Total Activo

In [14]:
data['Dot_dudosos'] = data['Provision for Loan Losses']/data['Total Assets']
len(data[data['Dot_dudosos'].isnull()])

39

## Variaciones en los ratios

A continuación vamos a incorporar como variable la variación de cada ratio con respecto al periodo anterior. Para ello primero aseguramos el orden adecuado de la tabla

In [15]:
data.sort_values(['Ticker','Fiscal Year','Fiscal Period'], ascending=True, inplace=True)

Despues incorporamos en cada fila el valor del ratio del periodo anterior, siempre que el Ticker no varíe.

In [16]:
#Definimos una función que genere subtablas por Ticker y en ellas haga un shift para incorporar en cada línea el
#valor de un ratio dado del periodo anterior.

def ratio_ant(ratio,data):
    table_1=pd.DataFrame()
    for ticker in data.Ticker.unique():
        aux_table=data[data.Ticker==ticker]
        aux_table['var_%s'%(ratio)]=(aux_table[ratio].shift(1)/aux_table[ratio])-1
        table_1=table_1.append(aux_table)
    return table_1

In [17]:
#Aplicamos la función anterior para cada ratio

for column in ['PER','PBC','ROE','ROA','Deuda_FFPP','DeudaCP_FFPP','Dot_dudosos']:
    data=ratio_ant(column,data)

/home/pipe/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## Valor relativo de cada ratio

Una posible mejora del modelo consiste en considerar cada uno de los ratios no por su valor absoluto, sino como un valor relativo con respecto al resto de compañias del periodo.
Para ello vamos a obtener para cada periodo el percentil que ocupa cada ratio de cada compañía con respecto a las demás.

In [18]:
data.head(4)

,Ticker,Fiscal Year,Fiscal Period,Publish Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Interbank Assets,Short & Long Term Investments,Accounts & Notes Receivable,Net Loans,Net Fixed Assets,Total Assets,Total Deposits,Short Term Debt,Long Term Debt,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,Revenue,Provision for Loan Losses,Net Revenue after Provisions,Total Non-Interest Expense,Operating Income (Loss),Non-Operating Income (Loss),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common),Periodo,Price_d,Price_d_100,Publish_Date+180,Price_d+180,Price_d+180_100,Indice_d_100,Indice_d+180_100,Var_cotiz,Var_index,Etiqueta,Capit,PER,PBC,ROE,ROA,Deuda_FFPP,DeudaCP_FFPP,Dot_dudosos,var_PER,var_PBC,var_ROE,var_ROA,var_Deuda_FFPP,var_DeudaCP_FFPP,var_Dot_dudosos
0,C,2011,Q2,2011-08-05,2.908600e+09,2.997000e+09,27766000000,4.401570e+11,631923000000,4.069500e+10,6.131380e+11,NaN,1956626000000,8.663100e+11,4.862840e+11,3.524580e+11,1777981000000,312000000.0,103504000000,-1.087000e+09,8.585700e+10,178645000000,1956626000000,20622000000,-3.387000e+09,17235000000,-12936000000,4299000000,NaN,4299000000,-9.670000e+08,3332000000,71000000.0,3341000000,3341000000,2011Q2,30.33,75.185920,2012-02-01,28.67,71.070897,86.447130,96.574366,-0.054731,0.117149,Peor,8.821784e+10,26.404621,0.493816,0.018702,0.001708,4.695021,2.722069,-0.001731,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C,2011,Q3,2011-11-04,2.910800e+09,2.998600e+09,28950000000,4.499830e+11,607294000000,3.799200e+10,6.051870e+11,NaN,1935992000000,8.512810e+11,4.943740e+11,3.338240e+11,1756650000000,312000000.0,105591000000,-1.089000e+09,8.960200e+10,179342000000,1935992000000,20831000000,-3.351000e+09,17480000000,-12460000000,5020000000,NaN,5020000000,-1.278000e+09,3742000000,1000000.0,3771000000,3771000000,2011Q3,27.53,68.244918,2012-05-02,29.68,73.574616,86.284868,102.828194,0.078097,0.191729,Peor,8.013432e+10,21.250152,0.446824,0.021027,0.001948,4.617981,2.756599,-0.001731,0.242561,0.105170,-0.110571,-0.123371,0.016683,-0.012526,0.000084
2,C,2011,Q4,2012-02-24,2.915400e+09,3.003000e+09,28701000000,4.316330e+11,585147000000,2.777700e+10,6.171270e+11,NaN,1873878000000,8.659360e+11,4.355920e+11,3.235050e+11,1694305000000,312000000.0,105833000000,-1.071000e+09,9.052000e+10,179573000000,1873878000000,16152000000,-2.437000e+09,13715000000,-12528000000,1187000000,NaN,1187000000,-1.450000e+08,1042000000,-44000000.0,956000000,956000000,2011Q4,29.36,72.781358,2012-08-22,27.69,68.641547,97.810615,101.998539,-0.056880,0.042817,Peor,8.559614e+10,89.535715,0.476665,0.005324,0.000510,4.227233,2.425710,-0.001301,-0.762663,-0.062603,2.949641,2.818004,0.092436,0.136409,0.330934
3,C,2012,Q1,2012-05-04,2.926200e+09,3.014500e+09,26505000000,4.730060e+11,604373000000,3.944300e+10,6.190020e+11,NaN,1944423000000,9.060120e+11,4.745410e+11,3.110790e+11,1760700000000,312000000.0,105816000000,-8.830000e+08,9.331000e+10,183723000000,1944423000000,19406000000,-3.019000e+09,16387000000,-12319000000,4068000000,NaN,4068000000,-1.006000e+09,3062000000,-5000000.0,2931000000,2931000000,2012Q1,28.69,71.120476,2012-10-31,33.96,84.184432,101.357729,104.113830,0.183688,0.027192,Mejor,8.395268e+10,28.643015,0.456952,0.015953,0.001507,4.276111,2.582916,-0.001553,2.125918,0.043139,-0.666294,-0.661552,-0.011430,-0.060864,-0.162390

In [19]:
data = data.astype({'Fiscal Year':str})
data['Periodo'] = data['Fiscal Year'] + data['Fiscal Period']

In [20]:
len(data)

1021

In [21]:
#Definimos una función que genere subtablas por periodo y cada una calcule el cuantil de cada ratio de cada
#compañia

In [22]:
from scipy import stats

def my_quantile(ratio,data):
    table_1=pd.DataFrame()
    
    for periodo in data.Periodo.unique():
        aux_table=data[data.Periodo==periodo]
        aux_table['quantile_%s'%(ratio)]=0       
        
        for row in range(0,len(aux_table)):
            aux_table['quantile_%s'%(ratio)].iloc[row]=stats.percentileofscore(aux_table[ratio],
                                                                               aux_table[ratio].iloc[row])
        
        table_1=table_1.append(aux_table)
            
    return table_1

In [23]:
#Aplicamos la función anterior para cada ratio

for column in ['PER','PBC','ROE','ROA','Deuda_FFPP','DeudaCP_FFPP','Dot_dudosos']:
    data=my_quantile(column,data)

/home/pipe/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/pipe/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1942: RuntimeWarning: invalid value encountered in less
  left = np.count_nonzero(a < score)
/home/pipe/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1943: RuntimeWarning: invalid value encountered in less_equal
  right = np.count_nonzero(a <= score)
/home/pipe/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/home/pipe/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

## Variaciones en los cuantiles

A continuación vamos a incorporar como variable la variación de cada percentil con respecto al periodo anterior. Para ello primero aseguramos el orden adecuado de la tabla

In [24]:
data.sort_values(['Ticker','Fiscal Year','Fiscal Period'], ascending=True, inplace=True)

Despues incorporamos en cada fila el valor del ratio del periodo anterior, siempre que el Ticker no varíe.

In [25]:
#Definimos una función que genere subtablas por Ticker y en ellas haga un shift para incorporar en cada línea el
#valor de un cuantil dado del periodo anterior.

def ratio_ant(ratio,data):
    table_1=pd.DataFrame()
    for ticker in data.Ticker.unique():
        aux_table=data[data.Ticker==ticker]
        aux_table['var_%s'%(ratio)]=(aux_table[ratio]-aux_table[ratio].shift(1))
        table_1=table_1.append(aux_table)
    return table_1

In [26]:
#Aplicamos la función anterior para cada ratio

for column in ['quantile_PER','quantile_PBC','quantile_ROE','quantile_ROA','quantile_DeudaCP_FFPP','quantile_Dot_dudosos']:
    data=ratio_ant(column,data)

/home/pipe/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [27]:
data[data.Ticker=='C'].head(10)

,Ticker,Fiscal Year,Fiscal Period,Publish Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Interbank Assets,Short & Long Term Investments,Accounts & Notes Receivable,Net Loans,Net Fixed Assets,Total Assets,Total Deposits,Short Term Debt,Long Term Debt,Total Liabilities,Preferred Equity,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,Revenue,Provision for Loan Losses,Net Revenue after Provisions,Total Non-Interest Expense,Operating Income (Loss),Non-Operating Income (Loss),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common),Periodo,Price_d,Price_d_100,Publish_Date+180,Price_d+180,Price_d+180_100,Indice_d_100,Indice_d+180_100,Var_cotiz,Var_index,Etiqueta,Capit,PER,PBC,ROE,ROA,Deuda_FFPP,DeudaCP_FFPP,Dot_dudosos,var_PER,var_PBC,var_ROE,var_ROA,var_Deuda_FFPP,var_DeudaCP_FFPP,var_Dot_dudosos,quantile_PER,quantile_PBC,quantile_ROE,quantile_ROA,quantile_Deuda_FFPP,quantile_DeudaCP_FFPP,quantile_Dot_dudosos,var_quantile_PER,var_quantile_PBC,var_quantile_ROE,var_quantile_ROA,var_quantile_DeudaCP_FFPP,var_quantile_Dot_dudosos
0,C,2011,Q2,2011-08-05,2.908600e+09,2.997000e+09,27766000000,4.401570e+11,631923000000,4.069500e+10,6.131380e+11,NaN,1956626000000,8.663100e+11,4.862840e+11,3.524580e+11,1777981000000,3.120000e+08,103504000000,-1.087000e+09,8.585700e+10,178645000000,1956626000000,20622000000,-3.387000e+09,17235000000,-12936000000,4299000000,NaN,4299000000,-9.670000e+08,3332000000,71000000.0,3341000000,3341000000,2011Q2,30.33,75.185920,2012-02-01,28.67,71.070897,86.447130,96.574366,-0.054731,0.117149,Peor,8.821784e+10,26.404621,0.493816,0.018702,0.001708,4.695021,2.722069,-0.001731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.470588,14.705882,44.117647,35.294118,70.588235,85.294118,20.588235,NaN,NaN,NaN,NaN,NaN,NaN
1,C,2011,Q3,2011-11-04,2.910800e+09,2.998600e+09,28950000000,4.499830e+11,607294000000,3.799200e+10,6.051870e+11,NaN,1935992000000,8.512810e+11,4.943740e+11,3.338240e+11,1756650000000,3.120000e+08,105591000000,-1.089000e+09,8.960200e+10,179342000000,1935992000000,20831000000,-3.351000e+09,17480000000,-12460000000,5020000000,NaN,5020000000,-1.278000e+09,3742000000,1000000.0,3771000000,3771000000,2011Q3,27.53,68.244918,2012-05-02,29.68,73.574616,86.284868,102.828194,0.078097,0.191729,Peor,8.013432e+10,21.250152,0.446824,0.021027,0.001948,4.617981,2.756599,-0.001731,0.242561,0.105170,-0.110571,-0.123371,0.016683,-0.012526,0.000084,14.705882,8.823529,52.941176,38.235294,70.588235,85.294118,14.705882,-11.764706,-5.882353,8.823529,2.941176,0.000000,-5.882353
2,C,2011,Q4,2012-02-24,2.915400e+09,3.003000e+09,28701000000,4.316330e+11,585147000000,2.777700e+10,6.171270e+11,NaN,1873878000000,8.659360e+11,4.355920e+11,3.235050e+11,1694305000000,3.120000e+08,105833000000,-1.071000e+09,9.052000e+10,179573000000,1873878000000,16152000000,-2.437000e+09,13715000000,-12528000000,1187000000,NaN,1187000000,-1.450000e+08,1042000000,-44000000.0,956000000,956000000,2011Q4,29.36,72.781358,2012-08-22,27.69,68.641547,97.810615,101.998539,-0.056880,0.042817,Peor,8.559614e+10,89.535715,0.476665,0.005324,0.000510,4.227233,2.425710,-0.001301,-0.762663,-0.062603,2.949641,2.818004,0.092436,0.136409,0.330934,82.352941,5.882353,14.705882,8.823529,73.529412,88.235294,20.588235,67.647059,-2.941176,-38.235294,-29.411765,2.941176,5.882353
3,C,2012,Q1,2012-05-04,2.926200e+09,3.014500e+09,26505000000,4.730060e+11,604373000000,3.944300e+10,6.190020e+11,NaN,1944423000000,9.060120e+11,4.745410e+11,3.110790e+11,1760700000000,3.120000e+08,105816000000,-8.830000e+08,9.331000e+10,183723000000,1944423000000,19406000000,-3.019000e+09,16387000000,-12319000000,4068000000,NaN,4068000000,-1.006000e+09,3062000000,-5000000.0,2931000000,2931000000,2012Q1,28.69,71.120476,2012-10-31,33.96,84.184432,101.357729,104.113830,0.183688,0.027192,Mejor,8.395268e+10,28.643015,0.456952,0.015953,0.001507,4.276111,2.582916,-0.001553,2.125918,0.043139,-0.666294,-0.661552,-0.011430,-0.060864,-0.162390,17.647059,5.882353,38.235294,26.470588,73.529412,88.235294,11.764706,-64.705882,0.000000,23.529412,17.647059,0.000000,-8.823529
4,C,2012,Q2,2012-08-03,2.926600e+09,3.015000e+09,33927000000,4.277180e+11,616172000000,3.534000e+10,6.273570e+11,NaN,1916451000000,9.143080e+11,4.615000e+11,2.883340e+11,1730612000000,3.120000e+08,105991000000,-8.590000e+08,9.621600e+10,185839000000,1916451000000,18387000000,-2.696000e+09,15691000000,-11994000000,3697000000,NaN,3697000000,-7.180000e+08,2979000000,7000000.0,2946000000,2946000000,2012Q2,24.89,61.700545,2013-01-30,38.11,94.471988,100.863452,112.248521,0.531137,0.112876,Mejor,7.284307e+10,24.726094,0.391969,0.015852,0.001537,4.034858,2.483332,-0.001407,0.158412,0.165788,0.006367,-0.019404,0.059792,0.040101,0.103698,11.764706,2.941176,29.411765,17.647059,73.529412,88.235294,14.705882,-5.882353,-2.941176,-8.823529,-8.823529,0.000000,2.941176
5,C,2012,Q3,2012-11-06,2.926800e+09,3.015300e+09,33802000000,4.475700e+11,610675000000,3.107700e+10,6.325070e+11,NaN,1931346000000,9.446440e+11,4.589000e+11,2.718620e+11,1742608000000,3.120000e+08,106232000000,-8.510000e+08,9.665000e+10,188738000000,1931346000000,13703000000,-2.620000e+09,11083000000,-12092000000,-1009000000,NaN,-1009000000,1.494000e+09,485000000,8000000.0,468000000,468000000,2012Q3,34.95,86.638572,2013-05-05,42.69,105.825483,105.704619,118.087877,0.221459,0.117150,Mejor,1.022917e+11,218.571923,0.541977,0.002480,0.000242,3.871833,2.431413,-0.001357,-0.886874,-0.276780,5.393069,5.343797,0.042105,0.021354,0.037005,94.117647,5.882353,8.823529,8.823529,73.529412,88.235294,11.764706,82.352941,2.941176,-20.588235,-8.823529,0.000000,-2.941176
6,C,2012,Q4,2013-03-01,2.942800e+09,3.017200e+09,36453000000,3.634450e+11,633255000000,2.249000e+10,6.300090e+11,NaN,1864660000000,9.305600e+11,4.358250e+11,2.394630e+11,1673663000000,2.562000e+09,106421000000,-8.470000e+08,9.780900e+10,190997000000,1864660000000,17694000000,-2.994000e+09,14700000000,-13631000000,1069000000,NaN,1069000000,2.230000e+08,1292000000,-68000000.0,1196000000,1196000000,2012Q4,38.27,94.868617,2013-08-28,43.92,108.874566,114.299774,133.978091,0.147635,0.172164,Peor,1.126210e+11,94.164679,0.589648,0.006262,0.000641,3.535595,2.281842,-0.001606,1.321167,-0.080846,-0.604012,-0.622207,0.095101,0.065548,-0.155132,91.176471,5.882353,5.882353,8.823529,73.529412,88.235294,11.764706,-2.941176,0.000000,-2.941176,0.000000,0.000000,0.000000
7,C,2013,Q1,2013-05-03,3.040100e+09,3.044700e+09,31150000000,4.136530e+11,613180000000,2.523500e+10,6.226370e+11,NaN,1881734000000,9.337620e+11,4.497710e+11,2.343260e+11,1686395000000,3.137000e+09,106692000000,-9.910000e+08,1.015800e+11,195339000000,1881734000000,20248000000,-2.459000e+09,17789000000,-12288000000,5501000000,NaN,5501000000,-1.570000e+09,3931000000,-33000000.0,3808000000,3808000000,2013Q1,42.69,105.825483,2013-10-30,45.35,112.419435,118.087877,144.746768,0.062310,0.225755,Peor,1.297819e+11,34.081373,0.664393,0.019494,0.002024,3.502101,2.302515,-0.001307,1.762937,-0.112502,-0.678784,-0.683048,0.009564,-0.008978,0.228717,26.470588,14.705882,29.411765,23.529412,73.529412,88.235294,5.882353,-64.705882,8.823529,23.529412,14.705882,0.000000,-5.882353
8,C,2013,Q2,2013-08-02,3.040700e+09,3.046300e+09,31145000000,4.212330e+11,606910000000,3.348400e+10,6.221610e+11,NaN,1883988000000,9.384270e+11,4.617860e+11,2.209590e+11,1686162000000,4.293000e+09,106907000000,-1.075000e+09,1.057250e+11,197826000000,1883988000000,20488000000,-2.024000e+09,18464000000,-12149000000,6315000000,NaN,6315000000,-2.127000e+09,4188000000,30000000.0,4182000000,4182000000,2013Q2,48.18,119.434804,2014-01-29,43.72,108.378780,141.988969,148.130539,-0.092570,0.043254,Peor,1.465009e+11,35.031307,0.740554,0.021140,0.002220,3.451240,2.334304,-0.001074,-0.027117,-0.102844,-0.077838,-0.088340,0.014737,-0.013618,0.216376,17.647059,5.882353,47.058824,41.176471,70.588235,88.235294,2.941176,-8.823529,-8.823529,17.647059,17.647059,0.000000,-2.941176
9,C,2013,Q3,2013-11-01,3.034300e+09,3.040900e+09,32810000000,4.463380e+11,595247000000,2.497600e+10,6.369460e+11,NaN,1899511000000,9.554600e+11,4.543310e+11,2.215930e+11,1696772000000,5.243000e+09,107061000000,-1.472000e+09,1.088120e+11,202739000000,1899511000000,17904000000,-1.959000e+09,15945000000,-11679000000,4266000000,NaN,4266000000,-1.080000e+09,3186000000,92000000.0,3227000000,3227000000,2013Q3,44.32,109.866138,2014-04-30,43.57,108.006941,143.046299,149.682214,-0.016922,0.046390,Peor,1.344802e+11,41.673435,0.663317,0.015917,0.001699,3.333961,2.240965,-0.001031,-0.159385,0.116442,0.328125,0.306618,0.035177,0.041651,0.041693,32.352941,2.941176,23.529412,17.647059,73.529412,88.235294,2.941176,14.705882,-2.941176,-23.529412,-23.529412,0.000000,0.000000

In [28]:
data.to_csv('../tablas/dataformodel.csv', index=False)